# Generated by Django 5.0.6 on 2024-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tableossec',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('rule_level', models.IntegerField(default=None, null=True)),
                ('rule_comment', models.CharField(default=None, max_length=255, null=True)),
                ('rule_sidid', models.IntegerField(default=None, null=True)),
                ('rule_firedtimes', models.IntegerField(default=None, null=True)),
                ('rule_groups', models.CharField(default=None, max_length=255, null=True)),
                ('location', models.CharField(default=None, max_length=300, null=True)),
                ('hostname', models.CharField(default=None, max_length=300, null=True)),
                ('program_name', models.CharField(default=None, max_length=300, null=True)),
                ('decoder_desc', models.TextField(default=None, null=True)),
                ('agent_name', models.CharField(default=None, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('logfile', models.CharField(default=None, max_length=300, null=True)),
                ('id', models.CharField(default=None, max_length=255, null=True)),
                ('prediction_ml', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tableossec',
            },
        ),
        migrations.CreateModel(
            name='Tablessnort',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('alert', models.CharField(max_length=1000, null=True)),
                ('Prediction_ml', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'tablessnort',
            },
        ),
    ]
